name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3

    - name: dependencies
      run: |
        dkp-pacman -S switch-dev --noconfirm
        git config --global --add safe.directory /__w/nxmp/nxmp
        git submodule update --init --recursive
        git clone --recursive https://github.com/sahlberg/libnfs.git
        cd libnfs && make install
        cd ..

    - name: make clean
      run: |
        make clean 

    - name: final
      run: | 
        make
      
    - uses: actions/upload-artifact@master
      with:
        name: nxmp
        path: build
